export const ADD_PLAYER = 'ADD_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const RESET_SCORES = 'RESET_SCORES';
export const RESET_BOARD = 'RESET_BOARD';
export const UNDO_MOVE = 'UNDO_MOVE';
export const MODIFY_LABELS = 'MODIFY_LABELS';
export const RANDOMIZE_LABELS = 'RANDOMIZE_LABELS';
export const RANDOMIZE_PLAYERS_ORDER = 'RANDOMIZE_PLAYERS_ORDER';
export const TOGGLE_MUTE = 'TOGGLE_MUTE';

